nhsuk/cervical-screening-interim

app/views/v12/CSSE-tool/CSSE-create-step10.html
app/views/v12/CSSE-tool/CSSE-create-step12.html

update file output page

---

app/views/v12/reports/pnl-responses/enter-date.html
app/views/v12/reports/pnl-responses/refine-report.html

small updates

---

app/assets/images/acc-def-1.csv
app/assets/images/acc-def-2.csv
app/assets/images/accumulated-deferrals-all-ccg.csv
app/assets/images/accumulated-deferrals-individual-ccg.csv
app/views/v12/reports/accumulated-deferrals/main-report-all-p1.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p2.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p3.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p4.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p5.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p6.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p7.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p8.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p9.html
app/views/v12/reports/accumulated-deferrals/main-report-individual.html

Updated acc deferrals csvs and links to csvs

---

app/routes.js
app/views/v12/reports/preview-age-change-report.html
app/views/v12/reports/preview-dob-change-report.html
app/views/v12/reports/preview-gender-change-report.html
app/views/v12/reports/preview-nhsno-change-report.html
app/views/v12/reports/report-demographic-gender-selected.html
app/views/v12/reports/report-letters-sent-drilldown.html

added demographic reports changes

---

app/views/v12/components/patient-info.html
app/views/v12/components/pnl-patient-2.html

Added repeat in 36 months to Last test

---

app/views/v12/admin/print-notifications-v2/print-gp-notifications.html
app/views/v12/admin/print-notifications-v2/print-patients-due-to-be-invited.html
app/views/v12/admin/print-notifications-v2/print-patients-who-have-not-responded.html
app/views/v12/admin/print-notifications-v3/print-gp-notifications.html
app/views/v12/admin/print-notifications-v3/print-patients-due-to-be-invited.html
app/views/v12/admin/print-notifications-v3/print-patients-who-have-not-responded.html
app/views/v12/admin/print-notifications/print-gp-notifications.html
app/views/v12/admin/print-notifications/print-patients-due-to-be-invited.html
app/views/v12/admin/print-notifications/print-patients-who-have-not-responded.html
app/views/v12/components/last-result.html
app/views/v12/components/patient-result-1-currentresult.html
app/views/v12/components/patient-result-1.html
app/views/v12/components/patient-result-2.html
app/views/v12/components/patient-result-3.html
app/views/v12/components/patient-result-4.html
app/views/v12/components/patient-result-duplicate-fraser-dup.html
app/views/v12/components/patient-result-duplicate-fraser-og.html
app/views/v12/components/patient-result-duplicate-rhodes-dup.html
app/views/v12/components/patient-result-duplicate-rhodes-og.html
app/views/v12/components/pnl-patient-2-no-result.html

Added more repeat in months

---

app/views/v12/admin/print-notifications-v3/print-patients-due-to-be-invited.html
app/views/v12/admin/print-notifications-v3/select-gp-practice.html
app/views/v12/email/notification-email-mvp.html
app/views/v12/patient/history-v4.html
app/views/v12/prior-notification/prior-notification-12-cease-reason.html
app/views/v12/prior-notification/prior-notification-12-defer-reason.html
app/views/v12/prior-notification/prior-notification-12-invite.html
app/views/v12/prior-notification/prior-notification-12.html

pnl wording updates

---

app/views/v12/components/pnl-patient-2-no-details.html
app/views/v12/patient/add-test-result/add-test-result-warning-1.html
app/views/v12/patient/add-test-result/add-test-result-warning-2.html
app/views/v12/patient/add-test-result/add-test-result-warning-3.html
app/views/v12/patient/add-test-result/add-test-result-warning-4.html

Added warning screens

---

app/views/v12/reports/lab-file-report/filter-reports.html
app/views/v12/reports/lab-file-report/preview-summary-csv.html
app/views/v12/reports/lab-file-report/report-lab-files-matched.html
app/views/v12/reports/preview-age-change-report.html
app/views/v12/reports/preview-dob-change-report.html
app/views/v12/reports/preview-nhsno-change-report.html

Content tweaks for reports

---

app/views/v12/reports-gp/cancer-audit/add-another.html
app/views/v12/reports-gp/cancer-audit/index.html
app/views/v12/reports-gp/cancer-audit/report-2-patients.html
app/views/v12/reports-gp/cancer-audit/report.html
app/views/v12/reports-gp/history-batch/index.html
app/views/v12/reports-gp/history-batch/manual.html
app/views/v12/reports-gp/history-batch/report.html
app/views/v12/reports-gp/history-batch/upload.html
app/views/v12/reports-gp/index.html

Updated admin reports to latest report patterns

---

app/views/v12/patient/add-test-result/add-test-result-warning-1.html
app/views/v12/patient/add-test-result/add-test-result-warning-2.html
app/views/v12/patient/add-test-result/add-test-result-warning-3.html
app/views/v12/patient/add-test-result/add-test-result-warning-4.html

Added line to warning designs

---

app/assets/images/Prior notification list (PNL) responses report 16-11-2021 to 16-12-2021 - 13.05 PM.csv
app/views/v12/reports/pnl-responses/enter-date.html
app/views/v12/reports/pnl-responses/refine-report.html

csv updates

---

app/views/v12/patient/add-hpv/add-hpv-vaccination.html
app/views/v12/patient/add-hpv/edit-hpv-vaccination.html
app/views/v12/patient/add-hpv/review-edit-hpv-vaccination.html

Updated back links on hpv

---

app/views/v12/reports/lab-file-report/choose-date.html
app/views/v12/reports/lab-file-report/preview-summary-csv.html
app/views/v12/reports/lab-file-report/report-lab-files-matched.html

Changes for UR

---

app/routes.js
app/views/v12/patient/additional-info-crm.html
app/views/v12/patient/additional-info.html
app/views/v12/patient/gp-info.html
app/views/v12/patient/history-v4.html
app/views/v12/patient/patient-summary-7.html

Crm comments

---

app/assets/images/unresolved.csv
app/views/v12/reports/lab-file-report/filter-reports.html

Minor changes post csas feedback

---

app/views/v12/patient/additional-info.html
app/views/v12/patient/gp-info.html
app/views/v12/patient/history-v4.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p1.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p2.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p3.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p4.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p5.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p6.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p7.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p8.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p9.html
app/views/v12/reports/accumulated-deferrals/main-report-individual.html

Updated prototype for testing

---

app/assets/images/accumulated-deferrals-all-ccg.csv
app/assets/images/accumulated-deferrals-individual-ccg-2.csv
app/assets/images/accumulated-deferrals-individual-ccg.csv
app/views/v12/reports/accumulated-deferrals/main-report-all-p1.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p2.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p3.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p4.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p5.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p6.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p7.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p8.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p9.html
app/views/v12/reports/accumulated-deferrals/main-report-individual.html

Updated report for testing

---

app/assets/images/Prior notification list (PNL) responses report 16-11-2021 to 16-12-2021 - 13.05 PM.csv
app/views/v12/reports/pnl-responses/enter-date.html
app/views/v12/reports/pnl-responses/enter-gp-practices.html
app/views/v12/reports/pnl-responses/refine-report.html

content and csv updates

---

app/views/v12/reports/accumulated-deferrals/main-report-individual.html

fixed prototype error

---

app/routes.js
app/views/v12/reports/reports.html
app/views/v12/reports/results-cutoff/choose-date.html
app/views/v12/reports/results-cutoff/report.html
app/views/v12/reports/sms-download/choose-date.html
app/views/v12/reports/sms-download/report-range.html
app/views/v12/reports/sms-download/report-today.html

Sms and result cutoff reports

---

app/views/v12/admin/index.html
app/views/v12/reports-gp/index.html

Updated reports hubs

---

app/assets/images/accumulated-deferrals-summary-all-ccg.csv
app/assets/images/accumulated-deferrals-summary-individual-ccg.csv
app/views/v12/reports/accumulated-deferrals/main-report-all-p1.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p2.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p3.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p4.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p5.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p6.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p7.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p8.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p9.html
app/views/v12/reports/accumulated-deferrals/main-report-individual.html

Acc def latest

---

app/views/v12/reports/reports.html
app/views/v12/reports/results-cutoff/choose-lab.html
app/views/v12/reports/results-cutoff/report.html

Report changes

---

app/views/v12/patient/patient-summary-7.html

more tweaks

---

app/routes.js
app/views/v12/components/report-add-missing.html
app/views/v12/components/report-corrupt.html
app/views/v12/components/report-missing.html
app/views/v12/reports/lab-file-report/choose-report.html
app/views/v12/reports/lab-file-report/missing-files/add-missing1.html
app/views/v12/reports/lab-file-report/missing-files/add-missing2.html
app/views/v12/reports/lab-file-report/missing-files/add-missing3.html
app/views/v12/reports/lab-file-report/missing-files/choose-date.html
app/views/v12/reports/lab-file-report/missing-files/missing-resolution1.html
app/views/v12/reports/lab-file-report/missing-files/missing-resolution2.html
app/views/v12/reports/lab-file-report/missing-files/range-report-added-file.html
app/views/v12/reports/lab-file-report/missing-files/range-report.html
app/views/v12/reports/lab-file-report/missing-files/resolution-step1.html
app/views/v12/reports/lab-file-report/missing-files/resolution-step2.html
app/views/v12/reports/lab-file-report/missing-files/single-date-report-added-file.html
app/views/v12/reports/lab-file-report/missing-files/single-date-report-resolved.html
app/views/v12/reports/lab-file-report/missing-files/single-date-report.html
app/views/v12/reports/reports.html

Missing files

---

app/views/v12/reports/sms-download/report-range.html
app/views/v12/reports/sms-download/report-today.html

Minor tweaks

---

app/views/v12/patient/patient-summary-7.html
app/views/v12/prior-notification/bypass-pnl/prior-notification-amend.html

logic updates

---

app/views/v11/prior-notification/prior-notification-12-forms-reinstate.html
app/views/v11/prior-notification/prior-notification-12-forms.html
app/views/v12/patient/gp-info.html
app/views/v12/patient/historic-data/choose-cipher.html
app/views/v12/patient/historic-data/cyau.html
app/views/v12/patient/historic-data/cytology-history.html
app/views/v12/patient/historic-data/demographics-history-lds.html
app/views/v12/patient/historic-data/demographics-history-wak.html
app/views/v12/patient/historic-data/demographics-history-wak2.html
app/views/v12/patient/historic-data/historic-data-ha.html
app/views/v12/patient/historic-data/historic-data.html
app/views/v12/patient/historic-data/next-test-due-date-audit.html
app/views/v12/patient/historic-data/notifications-history.html
app/views/v12/patient/historic-data/reg-audit.html
app/views/v12/patient/historic-data/test-details.html
app/views/v12/patient/history-v4.html
app/views/v12/patient/patient-summary-7.html

Archiving 2

---

app/views/v12/reports/accumulated-deferrals/main-report-all-p1.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p2.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p3.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p4.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p5.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p6.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p7.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p8.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p9.html
app/views/v12/reports/accumulated-deferrals/main-report-individual.html

Fixed acc def table

---

app/views/v12/patient/historic-data/cytology-history.html
app/views/v12/patient/patient-summary-7.html
app/views/v12/reports/reports.html

Hpv source

---

app/views/v12/reports/accumulated-deferrals/enter-date.html

content tweak

---

app/views/v12/components/pnl-patient-4.html
app/views/v12/patient/patient-summary-7.html
app/views/v12/prior-notification/bypass-pnl/prior-notification-amend.html
app/views/v12/prior-notification/bypass-pnl/prior-notification-reinstate-crm.html
app/views/v12/prior-notification/bypass-pnl/prior-notification-reinstate.html
app/views/v12/prior-notification/bypass-pnl/prior-notification-review-reinstate.html

updates to inset text

---

app/views/v12/patient/additional-info-p2.html
app/views/v12/patient/additional-info-p3.html
app/views/v12/patient/additional-info.html
app/views/v12/patient/delete-crm.html
app/views/v12/patient/edit-crm-review.html
app/views/v12/patient/edit-crm.html
app/views/v12/patient/paused-patients-summary.csv

Crmcomments

---

app/views/v12/patient/patient-summary-7.html

Updates to content

---

app/assets/sass/components/_panel-link.scss
app/views/v12/patient/historic-data/choose-cipher.html
app/views/v12/patient/historic-data/cyau.html
app/views/v12/patient/historic-data/cytology-history.html
app/views/v12/patient/historic-data/demographics-history-lds2.html
app/views/v12/patient/historic-data/demographics-history-wak2.html
app/views/v12/patient/historic-data/demographics-history-wak3.html
app/views/v12/patient/historic-data/historic-data.html
app/views/v12/patient/historic-data/next-test-due-date-audit.html
app/views/v12/patient/historic-data/notifications-history.html
app/views/v12/patient/historic-data/reg-audit-full.html
app/views/v12/patient/historic-data/reg-audit.html
app/views/v12/patient/historic-data/test-details.html
app/views/v12/patient/patient-summary-7.html
app/views/v12/patient/previous-addresses.html
app/views/v12/worklists-v12/manc-tanya-step2.html

Updates for testing

---

app/views/v12/patient/historic-data/notifications-history.html

Notif history updates

---

app/views/v12/patient/patient-summary-7.html

Added non-respond count

---

app/assets/images/manuallycancelledletter.csv
app/assets/images/sourcetype7.csv
app/assets/images/summary-7.csv
app/views/v12/reports/reports.html
app/views/v12/reports/results-to-letters/5-march-report.html
app/views/v12/reports/results-to-letters/index.html

Results letters

---

app/views/v12/patient/add-hpv/review-hpv-vaccination-2-no-edit-dose-1.html
app/views/v12/patient/add-hpv/review-hpv-vaccination-2-no-edit-dose-2.html
app/views/v12/patient/patient-summary-7.html

updated hpv review screens

---

app/views/v12/prior-notification/bypass-pnl/prior-notification-amend.html
app/views/v12/prior-notification/bypass-pnl/prior-notification-reinstate.html

content updates

---

app/views/v12/patient/historic-data/choose-cipher.html
app/views/v12/patient/historic-data/demographics-history-lds2.html
app/views/v12/patient/historic-data/demographics-history-wak3.html
app/views/v12/patient/historic-data/notifications-history.html
app/views/v12/patient/patient-summary-7.html
app/views/v12/worklists-v12/manc-tanya-step2.html

Archive more updates

---

app/views/v12/patient/historic-data/choose-cipher.html
app/views/v12/patient/historic-data/cyau-lds.html
app/views/v12/patient/historic-data/cyau-wak.html
app/views/v12/patient/historic-data/cytology-history.html
app/views/v12/patient/historic-data/demographics-history-lds.html
app/views/v12/patient/historic-data/demographics-history-wak.html
app/views/v12/patient/historic-data/demographics-history-wak2.html
app/views/v12/patient/historic-data/demographics-history-wak3.html
app/views/v12/patient/historic-data/historic-data.html
app/views/v12/patient/historic-data/next-test-due-date-audit.html
app/views/v12/patient/historic-data/notifications-history.html
app/views/v12/patient/historic-data/reg-audit-full.html
app/views/v12/patient/historic-data/reg-audit.html
app/views/v12/patient/historic-data/test-details.html

Updated migration date

---

app/views/v12/reports/accumulated-deferrals/enter-date.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p1.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p2.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p3.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p4.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p5.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p6.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p7.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p8.html
app/views/v12/reports/accumulated-deferrals/main-report-all-p9.html
app/views/v12/reports/accumulated-deferrals/main-report-individual.html
app/views/v12/reports/pnl-responses/enter-date.html
app/views/v12/reports/pnl-responses/enter-gp-practices.html
app/views/v12/reports/pnl-responses/refine-report.html
app/views/v12/reports/results-cutoff/choose-date.html
app/views/v12/reports/results-cutoff/choose-lab.html

Back link updates

---

app/views/v12/reports/lab-file-report/missing-files/report-file-added.html
app/views/v12/reports/lab-file-report/missing-files/report-lab-informed.html
app/views/v12/reports/lab-file-report/missing-files/report-resolved.html
app/views/v12/reports/lab-file-report/missing-files/single-date-report.html

copy change

---

app/views/v12/prior-notification/bypass-pnl/prior-notification-amend.html
app/views/v12/prior-notification/bypass-pnl/prior-notification-reinstate.html

content update

---

app/views/v12/prior-notification/bypass-pnl/prior-notification-amend-reason.html
app/views/v12/prior-notification/bypass-pnl/prior-notification-amend.html

radio button update

---

app/views/v12/reports/dummy-reg.html
app/views/v12/reports/reports.html

Added report

---

app/views/v12/reports/reports.html
app/views/v12/reports/results-to-letters/index.html
app/views/v12/reports/sms-download/choose-date.html
app/views/v12/reports/sms-download/report-range.html
app/views/v12/reports/sms-download/report-today.html

Report titles

---

app/assets/images/all-dummy-reg.csv
app/assets/images/non-resp.csv
app/views/v12/reports/dummy-reg.html

Added csvs and record row

---

app/views/v12/reports/lab-file-report/corrupt-files/all-corrupt.html
app/views/v12/reports/lab-file-report/filter-reports.html
app/views/v12/reports/lab-file-report/missing-files/add-missing-add-update.html
app/views/v12/reports/lab-file-report/missing-files/add-missing-file-received.html
app/views/v12/reports/lab-file-report/missing-files/add-missing-file-step1.html
app/views/v12/reports/lab-file-report/missing-files/add-missing-lab-informed.html
app/views/v12/reports/lab-file-report/missing-files/add-missing-mark.html
app/views/v12/reports/lab-file-report/missing-files/add-missing-not-resolved.html
app/views/v12/reports/lab-file-report/missing-files/add-missing-resolve1.html
app/views/v12/reports/lab-file-report/missing-files/add-missing-resolve2.html
app/views/v12/reports/lab-file-report/missing-files/add-missing-update.html
app/views/v12/reports/lab-file-report/missing-files/manual-file-added.html
app/views/v12/reports/lab-file-report/missing-files/manual-missing.html
app/views/v12/reports/lab-file-report/missing-files/possible-missing-date.html
app/views/v12/reports/lab-file-report/missing-files/possible-missing-lab-informed.html
app/views/v12/reports/lab-file-report/missing-files/possible-missing-resolved.html
app/views/v12/reports/lab-file-report/missing-files/possible-missing.html
app/views/v12/reports/lab-file-report/missing-files/view-file-details.html
app/views/v12/reports/lab-file-report/report-lab-files-matched.html

Missing files tweaks

---

app/views/v12/components/patient-result-4.html
app/views/v12/patient/pause-patient-new/add-info.html
app/views/v12/patient/pause-patient-new/add-test-details.html
app/views/v12/patient/pause-patient-new/add-test-result.html
app/views/v12/patient/pause-patient-new/add-test-type.html
app/views/v12/patient/pause-patient-new/pause-patient.html
app/views/v12/patient/pause-patient-new/review-action.html

Started paused patient

---

app/views/v12/patient/historic-data/cyau-lds.html
app/views/v12/patient/historic-data/cyau-wak.html
app/views/v12/patient/historic-data/cytology-history-with-details-error.html
app/views/v12/patient/historic-data/cytology-history-with-reg-error.html
app/views/v12/patient/historic-data/cytology-history.html
app/views/v12/patient/historic-data/demographics-history-lds2.html
app/views/v12/patient/historic-data/demographics-history-wak3.html
app/views/v12/patient/historic-data/next-test-due-date-audit.html
app/views/v12/patient/historic-data/reg-audit-full.html
app/views/v12/patient/historic-data/reg-audit.html
app/views/v12/patient/historic-data/test-details.html

Updated dates

---

app/views/v12/patient/additional-info.html
app/views/v12/patient/gp-info.html
app/views/v12/patient/history-v4.html
app/views/v12/patient/patient-summary-7.html

update to addinfo

---

app/views/v12/prior-notification/bypass-pnl/prior-notification-amend.html
app/views/v12/prior-notification/bypass-pnl/prior-notification-reinstate.html

removed cease option

---

app/assets/sass/components/_tables.scss
app/views/v12/components/create-dummy.html
app/views/v12/components/dummy-patient-banner.html
app/views/v12/patient/create-dummy/add-details.html
app/views/v12/patient/create-dummy/enter-crm.html
app/views/v12/patient/create-dummy/review-dummy.html
app/views/v12/patient/create-dummy/start.html
app/views/v12/patient/create-dummy/start2.html
app/views/v12/patient/create-dummy/start3.html
app/views/v12/patient/create-dummy/start4.html
app/views/v12/patient/dummy-patient-summary.html
app/views/v12/patient/pause-patient-new/add-info.html
app/views/v12/patient/pause-patient-new/add-test-details.html
app/views/v12/patient/pause-patient-new/add-test-result-2.html
app/views/v12/patient/pause-patient-new/add-test-type.html
app/views/v12/patient/pause-patient-new/pause-patient.html
app/views/v12/patient/pause-patient-new/review-action.html
app/views/v12/pds/search/search.html
app/views/v12/reports/manually-add-patients/report.html
app/views/v12/reports/reports.html

Manually add report

---

app/views/v12/components/patient-reinstate.html
app/views/v12/patient/patient-summary-7.html
app/views/v12/prior-notification/bypass-pnl/prior-notification-amend.html
app/views/v12/prior-notification/bypass-pnl/prior-notification-reinstate.html
app/views/v12/prior-notification/prior-notification-12-defer-reason.html

Commenting out Invited and Prior dates
